CREATE DATABASE IF NOT EXISTS employee_management;
USE employee_management;

CREATE TABLE IF NOT EXISTS release_management (
  id INT AUTO_INCREMENT PRIMARY KEY,
  release_month CHAR(7) NOT NULL,
  planned_release_date DATE NOT NULL,
  release_planning_status ENUM('Not Started', 'In Progress', 'Completed', 'Blocked', 'On Hold') DEFAULT 'Not Started',
  rts_handover_planned_date DATE NULL,
  release_tag VARCHAR(100) NOT NULL,
  application_name VARCHAR(150) NOT NULL,
  release_name VARCHAR(150) NOT NULL,
  build_program_manager VARCHAR(100) NULL,
  qe_program_manager VARCHAR(100) NULL,
  release_spoc VARCHAR(100) NULL,
  pre_deployment_checklist TEXT NULL,
  implementation_plan TEXT NULL,
  rollback_plan TEXT NULL,
  post_deployment_checklist TEXT NULL,
  rts_handover TEXT NULL,
  build_preparation_checklist TEXT NULL,
  test_case_checklist TEXT NULL,
  dor TEXT NULL,
  dod TEXT NULL,
  pre_deployment_checklist_execution ENUM('Not Started', 'In Progress', 'Completed', 'Blocked', 'Not Applicable') DEFAULT 'Not Started',
  post_deployment_checklist_execution ENUM('Not Started', 'In Progress', 'Completed', 'Blocked', 'Not Applicable') DEFAULT 'Not Started',
  release_encountered_issue BOOLEAN DEFAULT FALSE,
  issue_description TEXT NULL,
  remedy TEXT NULL,
  release_status ENUM('Planned', 'In Progress', 'Released', 'Failed', 'Rolled Back', 'Cancelled', 'On Hold') DEFAULT 'Planned',
  retro TEXT NULL,
  remarks TEXT NULL,
  auditor VARCHAR(100) NULL,
  created_by INT NULL,
  updated_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_release_tag (release_tag),
  INDEX idx_release_month (release_month),
  INDEX idx_planned_release_date (planned_release_date),
  INDEX idx_application_name (application_name),
  INDEX idx_release_status (release_status),
  INDEX idx_release_planning_status (release_planning_status),
  INDEX idx_release_created_by (created_by),
  INDEX idx_release_updated_by (updated_by)
);
