USE employee_management;

INSERT INTO release_management (
  release_month,
  planned_release_date,
  release_planning_status,
  rts_handover_planned_date,
  release_tag,
  application_name,
  release_name,
  build_program_manager,
  qe_program_manager,
  release_spoc,
  pre_deployment_checklist,
  implementation_plan,
  rollback_plan,
  post_deployment_checklist,
  rts_handover,
  build_preparation_checklist,
  test_case_checklist,
  dor,
  dod,
  pre_deployment_checklist_execution,
  post_deployment_checklist_execution,
  release_encountered_issue,
  issue_description,
  remedy,
  release_status,
  retro,
  remarks,
  auditor,
  created_by,
  updated_by
) VALUES
(
  '2026-05',
  '2026-05-28',
  'In Progress',
  '2026-05-27',
  'REL-2026-05-EMP-001',
  'Employee Management Portal',
  'May Payroll and Billing Release',
  'Ravi Kumar',
  'Anitha Rao',
  'Mahesh B',
  'Database backup completed; deployment checklist reviewed; rollback owner assigned.',
  'Deploy backend API, run migrations, deploy frontend build, validate billing and employee flows.',
  'Restore previous backend build and database backup if validation fails.',
  'Smoke test login, employee search, billing screens, invoice generation, and Release Management.',
  'RTS handover planned with support team after smoke testing.',
  'Build artifacts created and release notes attached.',
  'Regression checklist completed for billing, employees, projects, and incident tracker.',
  'All required approvals and dependencies are ready.',
  'Deployment complete, smoke tests pass, and support handover is done.',
  'In Progress',
  'Not Started',
  FALSE,
  NULL,
  NULL,
  'In Progress',
  NULL,
  'Sample active release record.',
  'Priya Sharma',
  NULL,
  NULL
),
(
  '2026-06',
  '2026-06-14',
  'Not Started',
  '2026-06-13',
  'REL-2026-06-INC-002',
  'Incident Tracker',
  'June Incident Workflow Release',
  'Sandeep Nair',
  'Lakshmi Menon',
  'Naveen P',
  'Checklist pending QE confirmation.',
  'Deploy incident dashboard fixes and comment workflow updates.',
  'Rollback to previous incident tracker bundle if create/update incident APIs fail.',
  'Validate dashboard graphs, incident create/edit, comments, and RCA dropdown.',
  'Support handover after UAT sign-off.',
  'Build preparation scheduled.',
  'Test cases drafted for dashboard, comments, RCA category, and filters.',
  'Business requirements approved and test environment available.',
  'All UAT scenarios pass and no severity 1 defects remain.',
  'Not Started',
  'Not Started',
  FALSE,
  NULL,
  NULL,
  'Planned',
  NULL,
  'Sample planned release record.',
  'Deepa Iyer',
  NULL,
  NULL
),
(
  '2026-04',
  '2026-04-20',
  'Completed',
  '2026-04-20',
  'REL-2026-04-CORE-003',
  'TeamPulse Core',
  'April Core Platform Release',
  'Kiran Patel',
  'Meera Joshi',
  'Arjun S',
  'Pre-deployment checklist completed and approved.',
  'Released role access updates, lookup fixes, and navigation improvements.',
  'Rollback was not required.',
  'Post-release validation completed by QE and support.',
  'Support handover completed with release notes.',
  'Build checklist completed.',
  'Regression tests completed for core admin modules.',
  'Release was ready with approvals complete.',
  'Production validation completed successfully.',
  'Completed',
  'Completed',
  TRUE,
  'Minor configuration mismatch found during validation.',
  'Updated environment configuration and re-ran smoke tests successfully.',
  'Released',
  'Improve environment checklist before future deployments.',
  'Sample completed release record with an encountered issue.',
  'Neha Gupta',
  NULL,
  NULL
)
ON DUPLICATE KEY UPDATE
  release_month = VALUES(release_month),
  planned_release_date = VALUES(planned_release_date),
  release_planning_status = VALUES(release_planning_status),
  rts_handover_planned_date = VALUES(rts_handover_planned_date),
  application_name = VALUES(application_name),
  release_name = VALUES(release_name),
  build_program_manager = VALUES(build_program_manager),
  qe_program_manager = VALUES(qe_program_manager),
  release_spoc = VALUES(release_spoc),
  pre_deployment_checklist = VALUES(pre_deployment_checklist),
  implementation_plan = VALUES(implementation_plan),
  rollback_plan = VALUES(rollback_plan),
  post_deployment_checklist = VALUES(post_deployment_checklist),
  rts_handover = VALUES(rts_handover),
  build_preparation_checklist = VALUES(build_preparation_checklist),
  test_case_checklist = VALUES(test_case_checklist),
  dor = VALUES(dor),
  dod = VALUES(dod),
  pre_deployment_checklist_execution = VALUES(pre_deployment_checklist_execution),
  post_deployment_checklist_execution = VALUES(post_deployment_checklist_execution),
  release_encountered_issue = VALUES(release_encountered_issue),
  issue_description = VALUES(issue_description),
  remedy = VALUES(remedy),
  release_status = VALUES(release_status),
  retro = VALUES(retro),
  remarks = VALUES(remarks),
  auditor = VALUES(auditor),
  updated_by = VALUES(updated_by);
